### PR TITLE
Matt

### PR DESCRIPTION
**Pull request by MSevey**
please review my added home page

### CODE REVIEW

**Review by nw0428 — CHANGES_REQUESTED** [review]
Give the forMatt folder a better name. Maybe "bootstrap"

**Comment by chanceencounter** [comment]
Why are there 91 changes.

**Comment by MSevey** [comment]
fixed index.html conflict

**Review by mklait — APPROVED** [review]

**Review by nw0428 — APPROVED** [review]
Your code organization sucks!

**Comment by MSevey** [comment]
updated folder name for better code organization.  Happy yet David?

**Pull request merged**
